### ISSUE TITLE
您好，可以在 Alpine Linux 的 musl 环境编译吗？

### ISSUE THREAD

**Issue by evalevil** [icpz/open-snell#1]
您好，可以在 Alpine Linux 的 musl 环境编译吗？

**Comment by F00cked** [comment]
$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/open-snell/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_c2a45/fast && /usr/bin/make -f CMakeFiles/cmTC_c2a45.dir/build.make CMakeFiles/cmTC_c2a45.dir/build
    make[1]: Entering directory '/root/open-snell/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_c2a45.dir/testCCompiler.c.o
    /usr/bin/clang    -o CMakeFiles/cmTC_c2a45.dir/testCCompiler.c.o   -c /root/open-snell/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_c2a45
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c2a45.dir/link.txt --verbose=1
    /usr/bin/clang      CMakeFiles/cmTC_c2a45.dir/testCCompiler.c.o  -o cmTC_c2a45
    clang-9: error: unable to execute command: Executable "ld" doesn't exist!
    clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_c2a45.dir/build.make:87: cmTC_c2a45] Error 1
    make[1]: Leaving directory '/root/open-snell/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_c2a45/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/root/open-snell/build/CMakeFiles/CMakeOutput.log".
See also "/root/open-snell/build/CMakeFiles/CMakeError.log".

**Comment by icpz** [comment]
I'll setup an environment to trace this.

**Comment by icpz** [comment]
I'll setup an environment to trace this.

**Comment by icpz** [comment]
Unfortunately alpine does not offer a prebuilt `libc++` package...
So if you want to build it on alpine, you need to build llvm by yourself
The following packages are required:
```
apk add cmake git build-base make pkgconfig openssl-dev libsodium-dev linux-headers
```

I'll find a better solution when I'm available.

**Comment by F00cked** [comment]
Thank you.

**Comment by F00cked** [comment]
Awesome, You build this case in busybox:glibc. Thank you very mush. 🎉🎉🎉

**Comment by icpz** [comment]
You are welcome. You can `docker pull icpz/snell-server` for amd64 arch.

Let's wait for gcc 10, which enables building on musl based alpine directly

**Comment by icpz** [comment]
Please check the [golang](https://github.com/icpz/open-snell/tree/golang) branch for further use.

Only snell v1 is supported currently, and v2 support will be added anyway.

The C++ port may not be maintained anymore.

**Comment by zc568917346** [comment]
您好@evalevil，我是您fork的school-dashboard项目的原始作者，由于项目中的package.json中含有敏感信息（邮箱），可以麻烦您删除敏感信息或者设为私有项目使用吗？谢谢
