### ISSUE TITLE
[Feature Request] Client Implement

### ISSUE THREAD

**Issue by TheWanderingCoel** [icpz/open-snell#2]
Hi, thanks for your great project! I want to ask if you have plan to support snell client so non-Surge user can use it?

**Comment by icpz** [comment]
I do have plan to implement snell-client. But I'm quite busy recently...
I'll get this done when I'm available.

**Comment by TheWanderingCoel** [comment]
Thank you very much~. Please notify me so I can add gui support for it

**Comment by TheWanderingCoel** [comment]
Any progress on this?

**Comment by icpz** [comment]
None... I'm working on my paper these weeks. Sorry.

**Comment by TheWanderingCoel** [comment]
> None... I'm working on my paper these weeks. Sorry.

No worry, thank you very much for your research and open-snell. I just implement a [snell client](https://github.com/Trojan-Qt5/snell-go) by golang based on trojan-go and clash.

**Comment by icpz** [comment]
Please check the [golang](https://github.com/icpz/open-snell/tree/golang) branch.
