### ISSUE TITLE
是否支持 tcp_fast_open

### ISSUE THREAD

**Issue by android0276** [icpz/open-snell#8]
Surge 官方编译的 snell 不支持 musl，只能在 glibc 上面运行，目前作者这个可以在 musl 上运行，就是不知道你这个版本是否支持 TFO

**Comment by icpz** [comment]
并不打算支持，因为 TFO 对延迟降低毫无意义，而且徒增特征。

**Comment by android0276** [comment]
亲，我这个不是用来科学上网，是用来连回家组内网用的，所以特征的问题影响不大，我这种场景延迟应该是能提升的吧，我那个 openwrt surge 官方的 snell 死活用不了

关于 TFO：我现在无视 tfo 黑名单强制启用tfo了 https://community.nssurge.com/d/866-tcp-fast-open

**Comment by icpz** [comment]
不是你强制启用 tfo 就会真的用 tfo 的，如果 tfo 握手不成功就会 Fallback 到普通 tcp 握手过程。

**Comment by android0276** [comment]
应该不影响吧，不支持tfo的话，他不理睬第一个syn包里面的信息就行吧，不会触发第一个syn包的重传吧，不是特别懂，支持tfo的就少一个包，不支持就正常tcp的逻辑

**Comment by android0276** [comment]
亲，这个能支持吗，不行的话我就把 issue 关掉了

**Comment by icpz** [comment]
你是要 amd64 的，还是 arm64 的

**Comment by android0276** [comment]
arm64 musl库

**Comment by icpz** [comment]
[snell-server.zip](https://github.com/icpz/open-snell/files/8512996/snell-server.zip)
可以试一下这个

**Comment by android0276** [comment]
我替换文件重启了下，tfo 可以了

20:54:19.634395 Rule matched: IP-CIDR 192.168.113.0/24
20:54:19.635228 Use the last successful address: 115.xxx.xxx.xxx
20:54:19.635590 Connecting with address: 115.xxx.xxx.xxx, use TCP Fast Open (force-enabled)
20:54:19.646228 Connected to address 115.xxx.xxx.xxx in 10ms
20:54:19.646345 TCP Fast Open was successful (tfo_syn_data_sent, tfo_syn_data_acked)
20:54:19.646513 TCP connection established
20:54:19.647065 HTTP request header found in the raw TCP connection.
20:54:19.657439 HTTP response header found in the raw TCP connection.
20:54:20.183520 Disconnect with reason: Closed by client

**Comment by android0276** [comment]
但是 udp 好像丢包概率比较大，转发 apple.com@8.8.8.8   50% 会失败，4G 和 Wifi 都一样

**Comment by icpz** [comment]
UDP 丢包无法控制，跟服务端的实现没什么关系。主要看线路。

**Comment by android0276** [comment]
那应该ok了，谢谢作者，很稳

**Comment by android0276** [comment]
这个东西为啥内存占用一直是600多M啊

**Comment by android0276** [comment]
4762     1 root     S     689m  18%   0% /root/snell/snell-server -c /root/snell/snell-server.conf

**Comment by android0276** [comment]
懂了~，小白一个，哈哈哈
